### ISSUE TITLE
Page admin/index.php non fonctionnelle

### ISSUE THREAD

**Issue by Spiritus44** [Jedediah04/TARDIS-Start#17]
Salut,
Je viens de m'en rendre compte, la page admin/index.php ne permet plus de modifier la destination des liens, ni le titre, ni l'icone.

Merci pour la future correction.

**Comment by Jedediah04** [comment]
C'est pourtant parfaitement fonctionnel chez moi.

**Comment by Spiritus44** [comment]
Je viens de recloner le dépot github actuel, je peux toujours pas changer n'importe quel paramètre de la page admin/index.php.

**Comment by Jedediah04** [comment]
As-tu bien fait un chown -R www-data:www-data sur les fichiers du dossier ?
Car j'ai fait un clone ce week-end et la modification fonctionne très bien.

**Comment by Spiritus44** [comment]
Hum oui, autant pour moi. Faudrait penser à l'écrire dans installation ^^.
