### ISSUE TITLE
Recherche non fonctionnelle ? 

### ISSUE THREAD

**Issue by LucasAdam** [Jedediah04/TARDIS-Start#2]
Yop, merci pour le partage :)

Petit soucis avec la recherche, d'apres le start.js je devrais pouvoir faire des recherches sur reddit/wiki/youtube... Mais j'ai beau essayer !y blabla ca ne marche pas :cry: 

Et sinon y'a un petit soucis dans ton arboressence, le dossier particles.js (qui d'apres le index.php devrait contenir les script pour les particules) est vide, c'est en realité le dossier particles qui les contient :+1: 

Autre petit truc, dans le start.js t'as laissé l'appel build(); alors que t'as enlevé la fonction ^^

A part ca, c'est beau ! Merci :)

Ps : Je suis winz de mondedie :smile:

**Comment by Jedediah04** [comment]
Hello :monkey_face: 

Le paramètre de recherche doit être placé en fin de requête : "image!i" pour faire une recherche sur Google Image.
Je corrige l'arborescence. Merci à toi.

**Comment by LucasAdam** [comment]
Merci pour l'info :)
