### ISSUE TITLE
Bug affichage disk et cpu

### ISSUE THREAD

**Issue by ghost** [Jedediah04/TARDIS-Start#24]
Bonjour,

Problème d'affichage et de calcul des données sur le pourcentage disk et cpu

![Erreur](http://i.imgur.com/Mqxob71.jpg)

J'utilise la dernier version de TardiStart.

Debian Linux 8.8
Kernel and CPU Linux 3.14.32-xxxx-grs-ipv6-64 on x86_64

Merci

**Comment by Spiritus44** [comment]
Salut,

As-tu toujours le problème ?

Pour le CPU, il faudrait que tu donnes plus d'informations :
Le nombre de core de ton processeur ?
Tu peux l'afficher avec : `grep -P '^processor' /proc/cpuinfo | wc -l` 

Tu peux aussi regarder la charge moyenne de ton serveur web avec la fonction PHP : `<?php echo sys_getloadavg(); ?>`

Concernant l'usage du HDD, cela t'affiche le pourcentage d'utilisation de ton répertoire /home.

**Comment by ghost** [comment]
Bonjour,
Toujours le même problème.
J'ai 4 coeur Intel(R) Atom(TM) CPU N2800 @ 1.86GHz,. La fonction ne php ne m'affiche rien. Juste "array" Il est censé affiché un tableau d'infos mais la rien.
Pour le HDD, oui je suis allé voir la fonction qui pointe sur /home mais elle n'affiche pas les bons chiffres. Je suis actuellement à 60% d'usage.
J'utilise docker. Peut etre que...

**Comment by Spiritus44** [comment]
Oui pardon, pour afficher la fonction sys_getloadavg, faire `<?php print_r(sys_getloadavg());?>` serait plus commode ;). Le `grep -P '^processor' /proc/cpuinfo|wc -l` te retournes bien 4 cores ?

Je connais pas trop docker, mais si tu fais la commande `docker stats` tu obtiens quoi en terme de CPU ?

Je fais quelques tests et je reviens vers toi :).

PS : Dans ton conteneur Docker tu as apache qui éxecute TardiStart ?

**Comment by ghost** [comment]
Oui avec cette commande, j'ai un résultat: 
Array
(
    [0] =&gt; 2.14697265625
    [1] =&gt; 1.7578125
    [2] =&gt; 1.5576171875
)
La commande m'indique bien 4 cores.
docker stats m'indique tout un tas d'informations sur mes conteneurs. 
http://i.imgur.com/jhH5xkc.png

Tardistart est présent dans le dossier www qui est exécuter par le docker nginx.

**Comment by Spiritus44** [comment]
Salut,

Concernant ton problème de CPU, je pense que ton problème vient des paramètres CPU de ton docker (visible avec "docker inspect < id du containeur > | grep Cpu").

Pour le soucis du disque dur, je pense qu'attacher un volume physique au docker devrait marcher : 
"docker run --name nginx -v /home:/home  -d <nom de l'image>"

**Comment by ghost** [comment]
Bonjour,

Pour le soucis de disque dur, c'est réglé. Par contre pour le cpu, j'obtiens le résultat suivant.

docker inspect nginx | grep Cpu
            "CpuShares": 0,
            "NanoCpus": 0,
            "CpuPeriod": 0,
            "CpuQuota": 0,
            "CpuRealtimePeriod": 0,
            "CpuRealtimeRuntime": 0,
            "CpusetCpus": "",
            "CpusetMems": "",
            "CpuCount": 0,
            "CpuPercent": 0,

Du coup comment paramétrer cela ?

**Comment by ghost** [comment]
Résolu sur mdd.

Procédure : 
Pour le quota de disque, monter /home dans le conteneur php

Pour le pourcentage du processeur, 
`function getCpuLoad() {
    // CPU USAGE
    $loads = sys_getloadavg();
    $core_nums = trim(shell_exec("grep -P '^processor' /proc/cpuinfo|wc -l"));
    $load = round($loads[0]/($core_nums + 1)*100, 0);
    return $load;
}
`

par 

`function getCpuLoad() {
    // CPU USAGE
    $loads = sys_getloadavg();
    $core_nums = trim(shell_exec("grep -E '^processor' /proc/cpuinfo|wc -l"));
    $load = round($loads[0]/($core_nums + 1)*100, 0);
    return $load;
}`
